- libratbox/src/openssl.c
Session tickets:
> When using session tickets, the TLS server stores its session-specific state in a session ticket and sends the session ticket to the TLS client for storing. The client resumes a TLS session by sending the session ticket to the server, and the server resumes the TLS session according to the session-specific state in the ticket. The session ticket is encrypted and authenticated by the server, and the server verifies its validity before using its contents.
> One particular weakness of this method with OpenSSL is that it always limits encryption and authentication security of the transmitted TLS session ticket to AES128-CBC-SHA256, no matter what other TLS parameters were negotiated for the actual TLS session. This means that the state information (the TLS session ticket) …
> openssl: Disable session tickets and session caching

- doc/ircd.conf.example
- doc/reference.conf
- include/s_conf.h
- modules/m_sasl.c
- src/newconf.c
- src/s_conf.c
This allows multiple improvements to m_sasl. With this change, the SASL
authentication gets aborted immediately when services are offline.
Additionally, we send the SASL ENCAP messages directly to the specified
SASL agent.
> m_sasl: add configuration option for the nick of the SASL agent

- modules/m_sasl.c
For future use by services-side logging and throttling.
> m_sasl: send information about the client connection

- libratbox/src/openssl.c
This is in accordance with RFC 7465
<https://tools.ietf.org/html/rfc7465>
Also correct the key exchange mechanism strings; these should be
prefixed with 'k'.
> Update ciphersuite string to prohibit RC4

- NEWS
- README.md
* Point to irc.freenode.net instead of irc.atheme.org. I know that it's
CNAME to chat, but I think it's preferable to use the irc. subdomain
to make it clear that it's IRC.
* Point to GitHub issue tracker instead of bugs-meta.atheme.org that
doesn't exist
* Remove mentioning of BUGS file and change README.FIRST to README.md as
the first doesn't exist and I think they are the same file.
> Update NEWS & README.md

- include/hostmask.h
- modules/m_stats.c
- src/hostmask.c
This function is not used anywhere else but m_stats, so should be put there.
> Relocate report_Klines to proper home

- modules/m_cap.c
Fixes https://github.com/atheme/charybdis/issues/110
> Remove trailing space in CAP ACK.

- configure.ac
- libratbox/configure.ac
AC_LANG_PROGRAM needs to be quoted when used within AC_*_IFELSE:
https://lists.gnu.org/archive/html/bug-autoconf/2011-04/msg00017.html
This fixes the following warnings:
$ autoreconf
configure.ac:298: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2729: _AC_RUN_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:639: AS_IF is expanded from...
../../lib/autoconf/general.m4:2748: AC_RUN_IFELSE is expanded from...
configure.ac:298: the top level
configure.ac:593: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from... …
> autoconf: Quote AC_LANG_PROGRAM when used within AC_*_IFELSE

- configure.ac
Configuring --with-topiclen=390 outputs a warning that TOPICLEN
has been limited to 390, but that's what was requested.
> configure: make TOPICLEN warn on >390, not >=390

- libratbox/include/ratbox_lib.h
UINT16_MAX may not be defined on some ancient hosts (FreeBSD 4.8)
It's used by libratbox/src/tools.c
> libratbox: define UINT16_MAX

- ircd/chmode.c
We're setting `flags` to `flags_list[3]` at the end of the loop, but the
array only has 3 elements. Unless the compiler optimises this away
(because `flags` will not be used again) we're accessing memory beyond
the end of the array.
With gcc-4.9:
```
chmode.c: In function 'set_channel_mode':
chmode.c:1548:54: warning: iteration 2u invokes undefined behavior [-Waggressive-loop-optimizations]
for(j = 0, flags = flags_list[0]; j < 3; j++, flags = flags_list[j])
^
chmode.c:1548:2: note: containing loop
for(j = 0, flags = flags_list[0]; j < 3; j++, flags = flags_list[j])
```
Explicitly set `flags = flags_list[j]` at the start of each loop
iteration, which will avoid referencing off the end of the array.
> ircd: chmode: Avoid referencing beyond the end of the flags_list array in set_channel_mode

- authd/res.c
The random_socket function isn't used, and the code can only be
compiled if the function is optimised away (because it's static
and unused) otherwise it will fail to link when "ipv4_addr" and
"ipv6_addr" are not found.
Fix this by modifying ipv4_addr and ipv6_addr so that they're not
external variables.
> authd: fix link failure in random_socket

- ssld/ssld.c
If change_connid is called with an unknown ID, respond by
reporting the new ID as closed instead of dereferencing
a NULL pointer.
> ssld: change_connid may be called with an unknown ID

- ircd/s_serv.c
- ircd/sslproc.c
It's possible for which_ssld to fail and return NULL, handle this in
start_ssld_connect and start_ssld_accept by returning NULL. The NULL
return value is already handled in all calls to start_ssld_accept,
so handle this for start_ssld_connect by reporting an error connecting.
Handle it in start_zlib_session by exiting the client.
> ircd: Handle which_ssld failure

- ssld/ssld.c
Cast the uint64_t format arguments to unsigned long long as
that's what the format string specifies.
> ssld: fix format string warnings for statistics

- bandb/sqlite3.c
This keeps annoying me whenever gcc complains about it
> bandb: sqlite3: check read() return value

- libratbox/Makefile.in
- libratbox/src/Makefile.in
without those, `make; make clean` is not idempotent.
i have found this patch lying around in my debian patch series, and it seems to still be relevant.
> add missing files to the clean target

- include/ircd.h
- ircd/version.c.SH
- libratbox/src/version.c.SH
we do this by removing the uname usage everywhere: it is not actually
used at runtime at all.
we keep the timestamp, because it is actually used in user_welcome()
but allow it to be overriden.
ideally, that timestamp would be completely removed, but I am not sure
what to put in its place, or if it would break some mysterious RFC (or
client!) if we remove that announcement.
closes #148.
> make build reproducible

- ircd/sslproc.c
- modules/m_stats.c
Iterate through the ssl daemons and report their status.
> ircd: add missing sslproc function ssld_foreach_info()

- include/parse.h
- ircd/parse.c
- modules/m_stats.c
It is a function with a single usage, that is used only for one specific stats command (which is used only on one line).
> parse: get rid of report_messages

- bandb/bandb.c
- ssld/ssld.c
These are in ssld and bandb. Also, the new text is more grammatically correct and removes the old CVS ID's.
> Remove some leftover ircd-ratbox references.

- modules/core/m_error.c
I see absolutely no reason why ircncmp was used here.
> core/m_error: Be consistent in strncmp usage

- ircd/s_user.c
chghost is supposed to make cycling user/hostnames transparent, so only send mode re-sets to clients that do not have chghost enabled. Otherwise, the client gets oped/voiced twice which doesn't make sense from a client standpoint.
> s_user: Don't send CHGHOST clients op/voice syncs

- autogen.sh
This avoids a needless dependence on bash.
> Invoke the standard system shell in autogen.sh

- include/client.h
- modules/m_sasl.c
This disconnects the user and adds a temporary reject if the same connection fails authentication too many times. (In v3, it uses the same counter as the regular reconnection throttle – one failed auth counts as one reconnection.)
"Unknown mechanism" failures are not affected by this.
Todo:
- <del>should registered clients (SASL Reauth) be exempted from this?</del> added throttling for Reauth
- should there be a separate failed auth attempt limit ([as in v1](https://github.com/charybdis-ircd/charybdis/compare/master...grawity:sasl-fail-throttle-v1))?
> limit failed SASL authentication attempts

- libratbox/src/openssl.c
- libratbox/src/openssl_ratbox.h
This is along the same line of work I've done to the MbedTLS backend.
The diff between the current MbedTLS backend and this OpenSSL backend is fairly small -- if you exclude the obvious differences between the libraries (required structures, function names, variable types, etc) the difference is almost non-existent.
I have done extensive testing but I don't claim to have caught everything wrong. It needs review.
A similar series of edits will be proposed for the GNUTLS backend soon; see also issue #215.
> Improve the OpenSSL backend

- modules/m_grant.c
Added 2 checks on "MyClient(source_p)", as the modules used to:
- Check if the source has "oper:grant" even if it's a remote client.
- Check if there was a proper shared{} block, even if the oper is a local client.
> m_grant.c - fixed remote grant support

- extensions/override.c
So, there's been a little debate about this feature being added to +p.
I can understand why it can be considered as a philosophical issue.
Here's why I still wanted to submit this pull-request:
- The umode +p is already considered as the immune user mode in Atheme.  
https://github.com/atheme/atheme/blob/master/modules/protocol/charybdis.c#L95
- You can already bypass bans and quiets with it, kick immunity would (in my opinion) be somewhat logical, as an oper usually uses +p to lift almost all limits.
- There is already cmode +M, but it is channel-wide and protects all opers, where +p is network-wide and would obviously protect only the oper having it.
For the unethical part, cmode +M is already granting an immunity and is not even visible to the users, except when +M channels are not …
> Added kick immunity to umode +p (oper-override)

- libratbox/src/gnutls.c
the [manpage][] says:
>  unsigned int * cert_max
>      Initially must hold the maximum number of certs. It will be updated
>      with the number of certs available.
ratbox doesn't actually initialize that variable, so gnutls naturally
fails. i would also recommend considering dynamically allocating the
cert list to deal with that error in other ways than failing to
configured SSL completely in GnuTLS. the apache gnutls module has a
similar problem and came up with a [patch][] to do exactly this which
you may want to consider.
but since our cert chain is only (!) 5 certs long, our itched is
scratch by this particular patch.
[manpage]: https://manpages.debian.org/jessie/gnutls-doc/gnutls_x509_crt_list_import.3.en.html
[patch]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=511573#35
> properly call gnutls_x509_crt_list_import

- extensions/sno_whois.c
When discussing #252 it was noticed that the comment is wrong.
> extensions/sno_whois.c: fix comment

- doc/oper-guide/cmodes.rst
I'd love to have that merged in 4.x but the oper guide is completely missing from there, see #258
> point users towards HELP EXTBAN for inline help

- librb/include/event-int.h
- librb/src/event.c
This avoids an issue where deleting an event inside the handler of a different event puts the event iteration in an invalid state.
> librb/event: delete indirectly via a dead flag

- include/modules.h
- ircd/modules.c
- modules/core/m_modules.c
Reloading modules sends CAP DEL followed by an immediate CAP NEW:
:staberinde.local CAP * DEL :account-tag
:staberinde.local CAP * NEW :account-tag
This isn't very nice. /modrestart is particularly bad. In order to avoid
doing this, we remember the capability set at the beginning of module
operations, compare that with the set afterwards, and report only the
differences with CAP {DEL,NEW}.
> Deferred capability notifications from modules

- extensions/Makefile.am
- extensions/override.c
- extensions/override_kick_immunity.c
I see kick immunity and override as quite different things, and want override but not kick immunity, but network administrators who want the new-old behaviour back can `loadmodule "extensions/override_kick_immunity"`.
> override: move kick immunity to its own module

- doc/technical/ts6-protocol.txt
- extensions/extb_oper.c
- include/client.h
- include/s_newconf.h
- ircd/client.c
- ircd/s_conf.c
- ircd/s_serv.c
- ircd/s_user.c
- modules/m_challenge.c
- modules/m_grant.c
- modules/m_oper.c
- modules/m_privs.c
- modules/m_whois.c
- tests/send1.c
Move opername and privset storage to struct User, so it can exist for
remote opers.
On /oper and when bursting opers, send:
:foo OPER opername privset
which sets foo's opername and privset. The contents of the privset on
remote servers come from the remote server's config, so the potential
for confusion exists if these do not match.
If an oper's privset does not exist on a server that sees it, it will
complain, but create a placeholder privset. If the privset is created by
a rehash, this will be reflected properly.
/privs is udpated to take an optional argument, the server to query, and
is now local by default:
/privs [[nick_or_server] nick]
> Propagate OPER

- ircd/s_conf.c
Currently if you gain or lose privileges due to a rehash your umodes won't update to reflect that, potentially leaving you with `a`, `p`, `H` etc. when you shouldn't have them (or not adding ones you should have) until you or someone else changes your mode (you can trigger this with `/mode $nick +`). Fix this the same way as for `/grant`, by calling `user_mode()` with noop arguments so it and any hooks get a chance to do things.
> Recheck umodes for opers after rehash

- extensions/override.c
We will spam about any uses of it, so this just seems like extra noise.
> override: don't spam about (un)setting the mode

- extensions/m_webirc.c
This is obviously a hack. Ideally webirc blocks would be their own thing. But since they're not...
My motivation for fixing this is tidiness, but this also closes a (very) small avenue for abuse in that someone with a webirc block could get into a passworded server without knowing the password to a regular iline.
> m_webirc: deny using webirc. as a real auth block

- extensions/m_webirc.c
- include/client.h
- ircd/s_user.c
Enforce `need_ssl` if present on the webirc auth block.
Allow the client to gain +Z upon registration only if the WEBIRC message comes with the `secure` option from IRCv3. If the option is present but the connection is plaintext, send a helpful warning.
This could be seen as a regression, since web IRC gateways that don't send `secure` can't get +Z any more. I think this is technically correct—there was no way for such gateways to distinguish TLS connections, so we should assume the scarier possibility—but I'm happy to do something if there are sensible configurations that rely on the existing behaviour.
> m_webirc: improve TLS handling

- include/modules.h
- ircd/modules.c
- modules/core/m_modules.c
/modrestart used to be implemented as a normal command and could crash
when used remotely because it would reload m_encap, which was on the
call stack at the time. This was fixed in 41390bfe5f. However,
/modreload has exactly the same problem, so I'm giving it the
same treatment.
Incidentally: This bug was first discovered in ircd-seven, where the
`/mod*` commands themselves live in the core, so m_encap was the only way
the crash could happen (and it didn't most of the time, because m_encap
would only be moved if you got unlucky). But `/mod*` are in modules in
charybdis, so /modrestart would have unloaded the code it was in the
middle of executing. With that in mind, I'm not sure how it ever
appeared to work. It reliably crashes for me.
> m_modules: make modreload work like restart

- include/reject.h
- include/s_conf.h
- ircd/reject.c
- ircd/s_conf.c
- ircd/s_user.c
rejectcache entries can now use either a K-line aconf or a static string as a reason. This will be sent in a 465 numeric before the usual ERROR. In the case of K-lines, it resembles the 465 you would have been sent without being rejected:
```
; nc -s 127.6.6.6 127.0.0.1 5000
:staberinde.local 465 * :You are banned from this server- Temporary K-line 4320 min. - abc123 (2019/12/31 01.07)
ERROR :Closing Link: (*** Banned (cache))
; nc -s 127.128.0.0 127.0.0.1 5000
:staberinde.local 465 * :You are not authorised to use this server.
ERROR :Closing Link: (*** Banned (cache))
```
> Remember and send reasons for rejectcache rejections

- doc/ircd.conf.example
- doc/reference.conf
- include/s_conf.h
- ircd/newconf.c
- ircd/s_conf.c
When, with the server configured to show K-line reasons, a user matches a temporary K-line, they get a message like:
:staberinde.local 465 a :You are banned from this server- Temporary K-line 4320 min. - abc123 (2019/12/31 01.45)
which might be helpful in some cases, but is not necessarily information operators would want to reveal. It might also be misleading in cases where the K-line is subject to change or likely to be renewed, as is the case for DNSBL bans, for example.
With this option enabled, the message becomes:
:staberinde.local 465 a :You are banned from this server- abc123 (2019/12/31 01.45)
just like a permanent K-line.
This change also affects D-lines for the same reasons.
> Add config option to hide durations of temporary K/D-lines

- ircd/s_conf.c
Fixes a use-after-free introduced in 548e31d3b, which fixed a related use-after-free introduced in a9536f755.
I wonder how long I can keep this up?
> Remove from the list of propagated bans on expiry

- ircd/version.c.SH
Set `EXTERNAL_BUILD_TIMESTAMP` from `SOURCE_DATE_EPOCH`
to make the package build reproducible by default without
everyone having to discover the custom variable.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
This code assigns the plain integer to keep the code simple.
Otherwise we would have to deal with differences between GNU date
and BSD date or include extra build deps like perl or python.
> Set EXTERNAL_BUILD_TIMESTAMP from SOURCE_DATE_EPOCH

- ircd/reject.c
Since #298, rejects have a pointer to the K-line that caused them. We can use that to stop applying rejects if their corresponding K-line is no longer in effect.
Note that we could check if the K-line's expiry timer has run out here, but we don't, since the K-line is going to remain operational until it's visited by the ban expiry stuff.
> reject: Don't reject for expired K-lines

- ircd/client.c
- ircd/hostmask.c
Add missing sockhost check in check_one_kline and do the ipv4-in-ipv6 check everywhere we check klines. Also stop comparing ip4s with ip6s and pointlessly parsing the K-line mask for each loop.
> Make K-line checking more consistent

- extensions/extb_canjoin.c
- extensions/extb_hostmask.c
- include/channel.h
- include/match.h
- ircd/channel.c
- ircd/match.c
- modules/m_knock.c
Doing this made me notice just how wildly inefficient `$m` is. I think extban functions should get a context struct parameter where we can send the strings, instead of generating them from scratch for each invocation, but that'll be another PR.
> Don't match iline-spoofed IPs for channel bans

- doc/technical/hooks.txt
- extensions/Makefile.am
- extensions/invite_notify.c
- include/hook.h
- modules/m_invite.c
- tests/send1.c
My motivation for moving out invite-notify is primarily that I want the freedom to not load it, which doesn't seem ideal from a maintenance perspective, but I have tried to test it.
The reason for the rather ugly two-stage solution is that invites can be rejected at the target end, and notifying half the network about an invite that doesn't actually happen seems wrong. This approach has the disadvantage that, if the inviter or invitee quits at the wrong moment, the notification can get lost. I think that's less bad.
> Fix invite-notify and move it to an extension

- authd/res.c
Currently the DNS resolver handles CNAME by skipping that record in the answer and looking for the subsequent A/AAAA/PTR record.  There are other record types which could be handled in the same way, e.g. DNAME, but their presence currently causes the answer parsing to be abandoned.  A better approach would be to skip *any* other record and just use the first A, AAAA or PTR in the answer, regardless of what comes before it.
> Skip any unhandled DNS record type

- include/modules.h
- ircd/modules.c
Allows extensions to be reloaded at the (theoretical) expense of breaking "reloads" where the unloaded and loaded paths differ. I think that's arguably a good thing.
> Reload modules by path

- ircd/capability.c
Rejecting this meant that ownerdata for orphaned caps was not restored when those caps were un-orphaned, so reloading e.g. m_sasl would irreversibly disable its visibility hook.
> capability: accept new ownerdata for existing caps

- modules/m_ison.c
Prior to this, m_ison would report a nick as being online if a client that was not yet registered had chosen this nickname on the same server. This change adds a check to make sure the struct Client has a struct User associated with it, i.e. registration has occurred.
> m_ison: Do not report unregistered connections

- include/msgbuf.h
- ircd/msgbuf.c
- modules/m_alias.c
- tests/msgbuf_parse1.c
The introduction of msgbufs made aliases change, e.g., `SET PROPERTY foo  :bar` to `SET PROPERTY foo bar`. By storing just one extra piece of information in `struct MsgBuf`, a pointer to the end of the input string, we gain the ability to restore the input exactly, and can pass it to services exactly as we received it.
> m_alias: Preserve protocol framing characters

- authd/Makefile.am
- authd/provider.c
- authd/provider.h
- authd/providers/dnsbl.c
- doc/ircd.conf.example
- include/authproc.h
- include/client.h
- include/defaults.h
- ircd/authproc.c
- ircd/newconf.c
- ircd/s_conf.c
- ircd/s_user.c
- modules/m_stats.c
Key points:
- Previously, we used `blacklist` and `DNSBL` in different places to refer to DNSBLs.  For various reasons, it is preferable to use `DNSBL` to refer to DNSBLs.
- Accordingly, all uses are now harmonized as `DNSBL` and other variants thereof.
- The `blacklist{}` configuration block is still supported, but a deprecation warning is generated.
> rename blacklist{} to dnsbl{}

- modules/m_grant.c
granting a non-opered user makes everything sad otherwise
> m_grant: zero-initialize struct oper_conf

- include/hostmask.h
- ircd/hostmask.c
- ircd/newconf.c
- modules/m_dline.c
- modules/m_kline.c
- tests/Makefile.am
- tests/TESTS
- tests/hostmask1.c
Broadly, bans that already existed in some way are handled as before, but the kline and dline commands will refuse to add new bans that look like CIDR bans but have invalid prefix lengths.
> Improve [kd]line handling of invalid IP-like masks

- ircd/chmode.c
Commit d3fd88a406cae91cbbbdad1c0112075d004fee53 introduced `sendto_channel_local_priv()` as a useful refactoring of the `ONLY_OPERS` hack in `sendto_channel_local()`.
This works by introducing a new `priv` argument, which points to a string containing either the required privileges or `NULL`.
The same change, however, sends an empty string as the `priv` argument for unprivileged modes, causing modes to not be distributed.  So we change that `priv` argument to `NULL`.
Otherwise, `sendto_channel_local_priv()` will only distribute mode changes to opers only.  This is because `HasPrivilege(target_p, "")` will evaluate as false due to the target not being opered.
Thanks to Devin Brown for bisecting this issue.
> chmode: use NULL for priv argument when auspex:cmodes priv is not needed
